version: '3'
services:
  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:apple-desk-pen-13@postgres:5432/${PGDATABASE}
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_SCHEMAS: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
    depends_on:
      flyway:
        condition: service_completed_successfully
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .envrc
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - ./migrations:/migrations
  # Uncomment this if you want to persist the data.
  # volumes:
  #   - "./pgdata:/var/lib/postgresql/data"
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "8080:8080"
    environment:
      API_URL: http://localhost:3000/
  flyway:
    image: flyway/flyway
    container_name: flyway
    command: -user=${PGUSER} -password=${PGPASSWORD} migrate
    volumes:
      - ./migrations:/flyway/migrations
      - ./flyway.conf:/flyway/conf/flyway.conf
    env_file:
      - .envrc
    environment:
      FLYWAY_LOCATIONS: filesystem:/flyway/migrations
    depends_on:
      postgres:
        condition: service_healthy
  develop:
    image: postgres
    container_name: develop
    env_file:
      - .envrc
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
